const fs = require('fs');
const token = JSON.parse(fs.readFileSync('/Users/ta-shanto/.gemini/antigravity-ide/brain/eedb92f1-c8b7-4c20-95fe-33e85145e690/scratch/token.json', 'utf8') || '"{}"').token; // wait I don't have token...
